### PR TITLE
fix - Delay in password expiration after creating the vjailbreak vm upon first login

### LINKED ISSUE #997: User can login with cloudinit password to the Vjailbreak VM for the first few seconds and later it overwrites the password
### What steps did you take and what happened?

User can login with cloudinit password to the Vjailbreak VM for the first few seconds and later it overwrites the password.

Please refer attached screenshot, left one is logged in with cloud-init, later in the right side asking for password change.

Image

### What did you expect to happen?

Either password change enforcement or cloud-init password set.

### Environment

Version: v0.3.5-rc

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by meghansh-pf9**
## What this PR does / why we need it

Added credential setup inside the packer adding it as a daemon which runs before sshd, hence ensuring the expiration of password without any delay.

## Which issue(s) this PR fixes
fix - User can login with cloudinit password to the Vjailbreak VM for the first few seconds and later it overwrites the password 
fixes #997 

__testing__

image

**Systemctl Status**

image 
 <div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>

<ul>

<li>Introduces a new daemon that creates the ubuntu user and sets its password before SSH access, ensuring immediate password expiration, which enhances security during the initial login phase.</li>

<li>Comments out previous password setup commands to prevent conflicts, thereby improving security.</li>

<li>Addresses the issue of users being able to log in with the cloud-init password temporarily before it gets overwritten.</li>

<li>Overall, the changes enhance the user setup process for the Vjailbreak VM by improving security during initial login and addressing password management issues.</li>

</ul>

</div>

### CODE REVIEW

File: image_builder/scripts/install.sh [hunk 1]
```diff
@@ -48,9 +48,9 @@ set_default_password() {
   
   log "Setting default password for ubuntu user..."
   
-  sudo usermod -p $(openssl passwd -1 "password") ubuntu
-  sudo chage -d 0 ubuntu
-  sudo passwd --expire ubuntu
+  #  sudo usermod -p $(openssl passwd -1 "password") ubuntu
+  #  sudo chage -d 0 ubuntu
+  #  sudo passwd --expire ubuntu
```
Comment (OmkarDeshpande7) [inline image_builder/scripts/install.sh]: remove these lines if not needed

**Review by OmkarDeshpande7 — APPROVED** [review]
one small comment. LGTM otherwise
