### PR TITLE
L2 scaling support. Don't query metadataservice, get uuid from pod's nodename.

### LINKED ISSUE #1839: Migrations running on agent failing with "failed to attach volume"
### What steps did you take and what happened?

Migrations running on agent failing with "failed to attach volume"

When checked in controller logs, its trying to attach volumes to master instead of agent node -

Master ID - e602ca0f-3531-42ff-b027-a9277bd99ad2
Agent ID - 9fdfed95-b2f6-4fc5-afab-7904aa4d6351

```
2026/04/21 10:59:39 Attaching volumes to VM: Hard disk 1
2026/04/21 10:59:39 OPENSTACK API: Attaching volume 698e387d-1163-4741-b225-3d2518c6c116 to VM e602ca0f-3531-42ff-b027-a9277bd99ad2, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 10:59:47 OPENSTACK API: Waiting for volume attachment for volume 698e387d-1163-4741-b225-3d2518c6c116 to VM e602ca0f-3531-42ff-b027-a9277bd99ad2, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 10:59:47 OPENSTACK API: Waiting for volume attachment for volume 698e387d-1163-4741-b225-3d2518c6c116 to VM e602ca0f-3531-42ff-b027-a9277bd99ad2, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:02:17 failed to live replicate disks: failed to attach volume: failed to attach volume to VM: failed to wait for volume attachment: volume attachment not found within 150 seconds. Trying to perform cleanup
2026/04/21 11:02:17 Detaching volume Hard disk 1 from VM
2026/04/21 11:02:17 OPENSTACK API: Detaching volume 698e387d-1163-4741-b225-3d2518c6c116 from VM e602ca0f-3531-42ff-b027-a9277bd99ad2, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:02:17 OPENSTACK API: Waiting for volume 698e387d-1163-4741-b225-3d2518c6c116 to become available, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
Volume 698e387d-1163-4741-b225-3d2518c6c116 is still attached to server retrying 0 times
2026/04/21 11:02:28 Volume Hard disk 1 detached from VM
2026/04/21 11:02:28 Detaching volume Hard disk 2 from VM
2026/04/21 11:02:28 OPENSTACK API: Detaching volume 9bc11eb4-294b-4d09-9634-e9d8d575cd97 from VM e602ca0f-3531-42ff-b027-a9277bd99ad2, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:05:01 OPENSTACK API: Waiting for volume 9bc11eb4-294b-4d09-9634-e9d8d575cd97 to become available, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:05:02 Volume Hard disk 2 detached from VM
2026/04/21 11:05:03 OPENSTACK API: Deleting volume with ID 698e387d-1163-4741-b225-3d2518c6c116, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:05:03 Volume Hard disk 1 deleted
2026/04/21 11:05:03 OPENSTACK API: Deleting volume with ID 9bc11eb4-294b-4d09-9634-e9d8d575cd97, authurl https://pcd-punevjail.pf9.io/keystone/v3, tenant service
2026/04/21 11:05:03 Volume Hard disk 2 deleted
2026/04/21 11:05:03 Successfully deleted 1 snapshots with name 'migration-snap'
2026/04/21 11:05:04 Failed to migrate VM: failed to live replicate disks: failed to attach volume: failed to attach volume to VM: failed to wait for volume attachment: volume attachment not found within 150 seconds. 
VM Win2k19-automation was powered on after migration failure
2026/04/21 11:05:04 ----- Migration completed with errors at 2026-04-21T11:05:04Z for VM Win2k19-automation -----

### What did you expect to happen?

Should migrate properly

### Environment

main

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by spai-p9**
## Which issue(s) this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #1839 

## Special notes for your reviewer
```

2026/04/23 11:47:28 [0] Hard disk 1 (DeviceKey=2000): ubuntu-22-xfs.vmdk -> Volume ubuntu-22-xfs-Hard disk 1 (/dev/vde)
2026/04/23 11:47:28 [1] Hard disk 2 (DeviceKey=2001): ubuntu-22-xfs_1.vmdk -> Volume ubuntu-22-xfs-Hard disk 2 (/dev/vdf)
2026/04/23 11:47:28 Fetched vjailbreak settings for Changed Blocks Copy Iteration Threshold: 20
2026/04/23 11:47:29 Starting full disk copy [1/2]: Hard disk 1 (DeviceKey=2000)
2026/04/23 11:47:29   Source: ubuntu-22-xfs.vmdk
2026/04/23 11:47:30   Target: /dev/vde (Volume ID: 1169877d-28a1-4184-850f-cc68d6087823)
2026/04/23 11:47:30 Executing /usr/sbin/nbdcopy --progress=3 --target-is-zero nbd+unix:///?socket=/tmp/nbdkit-2432068857/nbdkit.sock /dev/vde
2026/04/23 11:47:31 Copying disk 0, Completed: 0%
2026/04/23 11:47:41 Copying disk 0, Completed: 5%
2026/04/23 11:48:01 Copying disk 0, Completed: 10%
2026/04/23 11:48:17 Copying disk 0, Completed: 15%
2026/04/23 11:48:26 Copying disk 0, Completed: 20%
```
## Testing done

_please add testing details (logs, screenshots, etc.)_

### CODE REVIEW

File: v2v-helper/pkg/utils/openstackopsutils.go [hunk 1]
```diff
@@ -126,6 +117,47 @@ func GetCurrentInstanceUUID() (string, error) {
...
+		return "", fmt.Errorf("failed to list vjailbreak nodes: %w", err)
+	}
+
+	for _, vjNode := range vjNodeList.Items {
+		if vjNode.Name == nodeName && vjNode.Status.OpenstackUUID != "" {
+			return vjNode.Status.OpenstackUUID, nil
+		}
+	}
+
+	return "", fmt.Errorf("no VjailbreakNode with OpenstackUUID found for node %s", nodeName)
```
Comment (OmkarDeshpande7) [inline v2v-helper/pkg/utils/openstackopsutils.go]:
```suggestion
	return "", fmt.Errorf("no VjailbreakNode with OpenstackUUID found for k8s node %s", nodeName)
```

**Review by OmkarDeshpande7 — COMMENTED** [review]
one small comment

**Review by OmkarDeshpande7 — APPROVED** [review]
lgtm
