### PR TITLE
Check the target IP Allocation Pool to determine if Source VM IP is Available and Handle Port Creation 409 Conflict (release)

### LINKED ISSUE #445: Backend: Handle Port Creation 409 Conflict: Reuse Existing Port or Fail Early with Validation
### What steps did you take and what happened?

We are currently encountering a 409 Conflict error during port creation, which typically happens when a port with the same name or configuration already exists. This can cause confusion and failed migrations or provisioning attempts.

### What did you expect to happen?

Re-use the existing port if it matches the expected configuration.

If the existing port is invalid or mismatched, fail early with a clear validation error.

Optionally, log a warning and suggest port cleanup if needed.

### Environment

v0.1.10

### vCenter version

NA 

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by sarika-p9**
## Which issue(s) this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #445, #427

## Testing done

image
image 
 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This PR fixes bugs in migration modules by improving validation checks and standardizing constants. It enhances the migration plan controller's MAC conflict detection logic and ensures consistent constant usage in credential and rolling migration utilities. These changes correct outdated comments and improve code reliability.

</div>

### CODE REVIEW

File: k8s/migration/internal/controller/migrationplan_controller.go [hunk 1]
```diff
@@ -340,108 +361,431 @@ func extractVCenterCredentials(secret *corev1.Secret) (username, password, host
...
+
+	totalVMs := 0
+	for _, batch := range migrationplan.Spec.VirtualMachines {
+		totalVMs += len(batch)
+	}
+
+	if len(allMigrations.Items) != totalVMs {
+		// Not all migration objects have been created yet, check again soon.
+		return ctrl.Result{RequeueAfter: 5 * time.Second}, nil
+	}
```
Comment (OmkarDeshpande7) [inline k8s/migration/internal/controller/migrationplan_controller.go:529]: What will be the status of MIgrationPlan until, all migration objects are created?

File: k8s/migration/internal/controller/migrationplan_controller.go [hunk 2]
```diff
@@ -340,108 +361,431 @@ func extractVCenterCredentials(secret *corev1.Secret) (username, password, host
...
+	// 		continue
+	// 	}
+	// 	macAllocated, err := utils.IsMacAllocatedInOpenStack(ctx, openstackClients.NetworkingClient, mac)
+	// 	if err != nil {
+	// 		return "", fmt.Errorf("failed to check MAC allocation: %w", err)
+	// 	}
+	// 	if macAllocated {
+	// 		return fmt.Sprintf("CONFLICT:MAC_ALREADY_ALLOCATED:MAC %s is already allocated", mac), nil
+	// 	}
+	// }
```
Comment (OmkarDeshpande7) [inline k8s/migration/internal/controller/migrationplan_controller.go:606]: Please remove all commented code

File: k8s/migration/pkg/constants/constants.go [hunk 3]
```diff
@@ -72,6 +72,9 @@ const (
 	// PauseMigrationLabel is the label for pausing rolling migration plan
 	PauseMigrationLabel = "vjailbreak.k8s.pf9.io/pause"
 
+	// TrueString is the string representation of boolean true
+	TrueString = "true"
```
Comment (OmkarDeshpande7) [inline k8s/migration/pkg/constants/constants.go:76]: I think there is already some constant for this, please check and try if you can reuse it

File: ui/src/api/migrations/model.ts [hunk 4]
```diff
@@ -122,6 +122,7 @@ export enum Phase {
   AwaitingAdminCutOver = "AwaitingAdminCutOver",
   Succeeded = "Succeeded",
   Failed = "Failed",
+  Blocked = "Blocked",
```
Comment (OmkarDeshpande7) [inline ui/src/api/migrations/model.ts:125]: What is the `Phase` of migration object in backend when UI is saying Blocked

File: k8s/migration/pkg/constants/constants.go (hunk 3 above)
Comment (OmkarDeshpande7) [reply k8s/migration/pkg/constants/constants.go:76]: https://github.com/platform9/vjailbreak/blob/1b741ce4ea85dfbdf858b2f71c60fb50aa7e2689/k8s/migration/pkg/utils/credutils.go#L54
okay, then please change here also - https://github.com/platform9/vjailbreak/blob/1b741ce4ea85dfbdf858b2f71c60fb50aa7e2689/k8s/migration/pkg/utils/credutils.go#L54

**Review by OmkarDeshpande7 — APPROVED** [review]
lgtm
