### PR TITLE
Filtering security group according to particular tenant 

### LINKED ISSUE #827: Security Groups for all tenants gets listed in the migration form
### What steps did you take and what happened?

When we select SG of a tenant while migrating to some other tenant then an error occurs

`Exceeded maximum number of retries. Exceeded max scheduling attempts 3 for instance 0ec3f6b2-ea7d-4159-b8f6-551d94175801. Last exception: Security group 2a7cda32-f750-4e5e-a25b-a876bd2b042a not found.`

### What did you expect to happen?

List SG only for selected tenant during migration.

### Environment

v0.3.1

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by sarika-p9**
## Which issue(s) this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #827 

## Testing done
image
image

<h3>Summary by Bito</h3>
This PR enhances OpenStack integrations by implementing tenant-specific security group filtering. It refactors credential utilities and OpenStack operations to utilize a more robust identity client, while adding improved error handling and removing redundant code paths.

</div>

### CODE REVIEW

File: k8s/migration/api/v1alpha1/openstackcreds_types.go [hunk 1]
```diff
@@ -53,12 +53,19 @@ type OpenStackCredsInfo struct {
...
+
 // OpenstackInfo contains information about OpenStack environment resources including available volume types and networks
 type OpenstackInfo struct {
-	VolumeTypes    []string `json:"volumeTypes,omitempty"`
-	VolumeBackends []string `json:"volumeBackends,omitempty"`
-	Networks       []string `json:"networks,omitempty"`
-	SecurityGroups []string `json:"securityGroups,omitempty"`
+	VolumeTypes    []string            `json:"volumeTypes,omitempty"`
+	VolumeBackends []string            `json:"volumeBackends,omitempty"`
+	Networks       []string            `json:"networks,omitempty"`
```
Comment (spai-p9) [inline k8s/migration/api/v1alpha1/openstackcreds_types.go:67]: nit: remove spaces added here

File: k8s/migration/api/v1alpha1/openstackcreds_types.go [hunk 2]
```diff
@@ -53,12 +53,19 @@ type OpenStackCredsInfo struct {
 	DomainName string
 }
 
+// SecurityGroupInfo holds the security group name and ID
+type SecurityGroupInfo struct {
+	Name              string `json:"name"`
+	ID                string `json:"id"`
+	RequiresIDDisplay bool   `json:"requiresIdDisplay"`
```
[the remark this answers is not in the document]
Comment (spai-p9) [reply k8s/migration/api/v1alpha1/openstackcreds_types.go:60]: I see ok sounds good.

File: k8s/migration/api/v1alpha1/openstackcreds_types.go (hunk 1 above)
Comment (sarika-p9) [reply k8s/migration/api/v1alpha1/openstackcreds_types.go:67]: these spaces are automatically generated because of this field change `[]SecurityGroupInfo`
