### PR TITLE
Setting up the default password for the agent nodes 

### LINKED ISSUE #1282: Not able to login to the agent node with the default password
### What steps did you take and what happened?

Scaled up the vjailbreak node and tried to login into the agent VM using the default password `password` specified in the logs but the login failed

### What did you expect to happen?

Upon entering the default password, login should have happened

### Environment

v0.3.6

### vCenter version

vSphere Client version 8.0.1.00300

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by meghansh-pf9**
## What this PR does / why we need it

Setting up the default password, into the agent node

fixes #1282

### CODE REVIEW

File: ui/src/pages/dashboard/ScaleUpDrawer.tsx [hunk 1]
```diff
@@ -269,8 +269,8 @@ export default function ScaleUpDrawer({ open, onClose, masterNode }: ScaleUpDraw
                 />
               </FormControl>
               <FormControl fullWidth>
-                <Typography variant="body1" style={{ color: 'red' }}>
-                  ⚠️ Please select a flavor with a disk size of at least 60GB.
+                <Typography variant="body1" style={{ color: 'yellow' }}>
+                  The VM will be created with 60GB disk size.
```
Comment (sharma-tapas) [inline ui/src/pages/dashboard/ScaleUpDrawer.tsx]: Remove this message, document that each agent needs 60GB free disk space either on shared/SAN or ephemeral storage.

**Review by sharma-tapas — COMMENTED** [review]
Minor: NIT
