### PR TITLE
Fix: Display RDM disk sizes correctly for disks smaller than 1 GB

### LINKED ISSUE #1081: RDM disk size shows 0GB if size is below 1GB
### What steps did you take and what happened?

RDM disk size shows 0GB if below 1GB

Image

### What did you expect to happen?

It should show 0.2 GB or 200 MB

### Environment

v0.3.6-rc

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by rijojohn85**
## What this PR does / why we need it

This PR fixes a display issue where RDM disks smaller than 1 GB were being shown as "0 GB" in the UI.
Problem: The current implementation uses Math.round() to convert bytes to GB, which rounds any disk size less than 0.5 GB down to 0. For example, a 200 MB disk (0.195 GB) was displayed as "0 GB" in the RDM Disk Configuration Panel.
Solution: Implemented a smart formatting function that:

- Displays disk sizes in MB for disks smaller than 1 GB (e.g., "200 MB")
- Displays disk sizes in GB with one decimal place for disks 1 GB and larger (e.g., "1.5 GB")
- Provides more accurate and user-friendly size representation

Impact: Users can now correctly see the actual size of their RDM disks

## Which issue(s) this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #1081

## Special notes for your reviewer

- The fix is localized to the RdmDiskConfigurationPanel.tsx component
- Changed from simple Math.round() division to a formatting function that intelligently chooses units (MB vs GB)
- This ensures sub-GB disks are displayed accurately without loss of information
- No changes to the underlying data model or API - this is purely a display/formatting fix

## Testing done

****
_please add testing details (logs, screenshots, etc.)_

200MB:
image

10GB:
image

1GB:
image

900MB:
image

1.3GB:
image

1MB:
image 
 <div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>

<ul>

<li>This pull request improves the RDM Disk Configuration Panel by implementing a new formatting function that accurately displays disk sizes.</li>

<li>Disks smaller than 1 GB are now shown in MB, while larger disks are displayed in GB with one decimal place.</li>

<li>This change resolves a previous issue where smaller disks were incorrectly displayed as '0 GB', significantly enhancing the user experience.</li>

<li>Overall, the update ensures users can accurately see the actual size of their RDM disks.</li>

</ul>

</div>

### CODE REVIEW

File: ui/src/components/RdmDiskConfigurationPanel.tsx [hunk 1]
```diff
@@ -115,7 +115,20 @@ export const RdmDiskConfigurationPanel: React.FC<RdmDiskConfigurationPanelProps>
                 if (!config) return null
 
                 const ownerVMs = disk.spec.ownerVMs
-                const diskSizeGB = Math.round(disk.spec.diskSize / (1024 * 1024 * 1024))
+                const formatDiskSize = (sizeInBytes: number): string => {
```
Comment (AbhijeetThakur) [inline ui/src/components/RdmDiskConfigurationPanel.tsx]: It currently returns undefined in a few cases, so your size Chip will show nothing. Pull it out of the render and implement it once.


```
const formatDiskSize = (bytes: number): string => {
  if (!bytes || bytes <= 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  const size = bytes / Math.pow(1024, i);
  return `${size.toFixed(1)} ${units[i]}`;
}

```

Comment (rijojohn85) [reply ui/src/components/RdmDiskConfigurationPanel.tsx]: Hi, 
I've updated the function a bit so it's safe when the size is very large and there is no out of index error. 
Moved the function to utils.ts
100TB:
image

10KB:
image

512 bytes:
image
