### PR TITLE
fix - Suse-11-4 - VM ends up in maintenance mode post migration

### LINKED ISSUE #1792: Suse-11-4 -  VM ends up in maintenance mode post migration
### What steps did you take and what happened?

Suse-11-4 -  VM lands up in maintenance mode post migration

Please find below pre and post migration -

Pre -

Image

Post -

Image
Image

### What did you expect to happen?

VM should boot properly post migration

### Environment

main

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by meghansh-pf9**
## What this PR does / why we need it

Implemented robust boot-time disk detection mechanism for Linux, ensuring backward compatibility with older kernels that lack hot-plug disk support.

## Which issue(s) this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #1792

### Disks post migration 
image

### CODE REVIEW

File: scripts/generate-mount-persistence.sh
Comment (OmkarDeshpande7) [inline scripts/generate-mount-persistence.sh:1]: Do we really need change to this file for these fixes?

File: v2v-helper/pkg/utils/openstackopsutils.go [hunk 1]
```diff
@@ -902,27 +920,9 @@ func (osclient *OpenStackClients) CreateVM(ctx context.Context, flavor *flavors.
 		time.Sleep(time.Duration(vjailbreakSettings.VMActiveWaitIntervalSeconds) * time.Second)
 	}
 
-	PrintLog(fmt.Sprintf("Server created with ID: %s, Attaching Additional Disks", server.ID))
+	// PrintLog(fmt.Sprintf("Server created with ID: %s, Attaching Additional Disks", server.ID))
```
Comment (OmkarDeshpande7) [inline v2v-helper/pkg/utils/openstackopsutils.go:923]: leftover debug?

**Review by OmkarDeshpande7 — APPROVED** [review]
one small comment, lgtm otherwise
