### PR TITLE
fix for long vm names

### LINKED ISSUE #656: Migrations go into pending state for VMs with long names
### What steps did you take and what happened?

Migrate a VM with a very long name (more than 50 characters), the Migration job went into Pending state with error like `Job.batch \"v2v-helper-some-random-vm-name\" is invalid: [metadata.labels: Invalid value: \"v2v-helper-some-random-vm-name\": must be no more than 63 characters`

### What did you expect to happen?

VM to migrate successfully

### Environment

v0.1.15

### vCenter version

8.0.0

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by OmkarDeshpande7**
## Which issue(s) this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #656 

## Testing done
Screenshot 2025-07-21 at 4 35 48 PM
Screenshot 2025-07-21 at 4 36 31 PM

 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This pull request addresses issues with long VM names by implementing hash-based naming strategies and standardizing label constants across migration controllers. It enhances the reliability of the migration process by improving naming consistency, refining error handling, and strengthening concurrency control in VMware machine operations.

</div>

### CODE REVIEW

File: k8s/migration/internal/controller/migrationplan_controller.go [hunk 1]
```diff
@@ -548,7 +556,7 @@ func (r *MigrationPlanReconciler) CreateJob(ctx context.Context,
 							{
 								Name:            "fedora",
 								Image:           v2vimage,
-								ImagePullPolicy: corev1.PullIfNotPresent,
+								ImagePullPolicy: corev1.PullAlways,
```
Comment (spai-p9) [inline k8s/migration/internal/controller/migrationplan_controller.go:559]: @OmkarDeshpande7 missed this why is it changed to pullalways?

Comment (OmkarDeshpande7) [reply k8s/migration/internal/controller/migrationplan_controller.go:559]: local change, good catch!
