### PR TITLE
Handled trailing slash in vCenter URL

### LINKED ISSUE #1306: vcenter URL does not work if there is a / in the end
### What steps did you take and what happened?

The vCenter URL does not work if it ends with a trailing “/”. The code should handle this by trimming any trailing “/” before using the URL

User should be able to provide url with "/" at the end

https://vcenter.phx.pnap.platform9.horse/

### What did you expect to happen?

User should be able to provide url with "/" at the end

### Environment

v0.3.8-rc

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by sarika-pf9**
## What this PR does / why we need it
This PR addresses an issue where providing a vCenter URL with a trailing slash (e.g., https://vcenter.example.com/) caused connection failures. The existing logic was blindly appending /sdk to the host string, resulting in malformed URL paths like //sdk, which triggered a 400 Bad Request from the vCenter API.

## Which issue(s) this PR fixes
fixes #1306 

## Testing done

https://github.com/user-attachments/assets/9bfed29a-e357-41c1-b034-7e44cfa53c3b

### CODE REVIEW

File: k8s/migration/pkg/utils/credutils.go [hunk 1]
```diff
@@ -472,16 +472,18 @@ func ValidateVMwareCreds(ctx context.Context, k3sclient client.Client, vmwcreds
...
+	if !strings.HasPrefix(rawHost, "http") {
+		rawHost = "https://" + rawHost
 	}
-	u, err := url.Parse(host)
+
+	u, err := url.Parse(rawHost)
 	if err != nil {
 		return nil, fmt.Errorf("failed to parse URL: %w", err)
 	}
+	u.Path = "/sdk"
```
Comment (roopakparikh) [inline k8s/migration/pkg/utils/credutils.go]: dont use string concatenation. Use url.JoinPath

File: pkg/validation/vmware/validate.go [hunk 2]
```diff
@@ -91,14 +91,23 @@ func Validate(ctx context.Context, k8sClient client.Client, vmwcreds *vjailbreak
 	datacenter := vmwareCredsinfo.Datacenter
 
 	// Normalize URL
-	if host[:4] != "http" {
-		host = "https://" + host
+	rawHost := strings.TrimSpace(host)
```
Comment (roopakparikh) [inline pkg/validation/vmware/validate.go]: This is copy pasted code from the code in the file above, why do we have similar looking functions, why not consolidate

File: pkg/vpwned/sdk/targets/vcenter/vcenter.go [hunk 3]
```diff
@@ -74,10 +74,16 @@ func findBootDevice(devices []types.BaseVirtualMachineBootOptionsBootableDevice)
 func (v *Vcenter) connect(ctx context.Context, a api.TargetAccessInfo) (*govmomi.Client, *find.Finder, error) {
 	logrus.Info("Connecting to vCenter...")
 	// Parse vCenter URL
-	u, err := url.Parse(fmt.Sprintf("https://%s/sdk", a.HostnameOrIp))
+	rawHost := strings.TrimSpace(a.HostnameOrIp)
```
Comment (roopakparikh) [inline pkg/vpwned/sdk/targets/vcenter/vcenter.go]: Same again ? Why do we hav ethe duplication ?

File: k8s/migration/pkg/utils/credutils.go (hunk 1 above)
Comment (sarika-pf9) [reply k8s/migration/pkg/utils/credutils.go]: made changes accordingly
