### PR TITLE
cluster conversion fixes for static esx IPs

### LINKED ISSUE #1057: Unable to persist the ESXi server IP and network config during cluster conversion.
### What steps did you take and what happened?

When the ESXi server is getting re-imaged with Ubuntu and onboarded in PCD via MAAS the process does not capture the ESXi server's original IP and network config details so as to configure the same on the Ubuntu host.
The vJailbreak process pushes one cloud-init(I guess: `k8s/migration/pkg/scripts/cloud-init.tmpl.yaml`) via MAAS which majorly has the host onboarding related steps via `pcdctl` command which are required to authorize the host in PCD. Prior to this the networking piece should get configured on the host for connectivity to work and host to get onboard.
The vJailbreak UI gives an option for the user to add their own cloud-int as well, however as per [this code](https://github.com/platform9/vjailbreak/blob/d82198077ca301a2919d38a7e5732775f1101bbb/k8s/migration/pkg/utils/bmprovisionerutils.go#L198) the vJailbreak's cloud-init takes precedence over the user provided cloud-init / data and thus user cannot setup networking on the host via their own cloud-init.

Also if there are multiple ESXi servers getting migrated who has static IP configuration(not DHCP) than there should be a process to capture each of the migrating server's networking details and configure it accurately on the Ubuntu host before applying the vjailbreak's inbuild cloud-init.

Also the process would first needs to check the interface naming mentioned in the blueprint's host network config like whether it is ensx/ethx/enpxx OR [interface].[vlan] OR bondx OR bonx.[vlan], etc and then that respective interface should get configured along with IP on it before applying the inbuild cloud-init.
If blueprin't host network config doesn't match the actual interface naming on the Ubuntu host, the onboarding fails.

### What did you expect to happen?

Explained above.

### Environment

vJailbreak version: v0.3.5

### vCenter version

NA

### Anything else you would like to add?

_No response_

### LINKED ISSUE #1168: cluster conversion process fails with error - "ESXi <IP> is not in MAAS" though it is added.
### What steps did you take and what happened?

Hello,
During the cluster conversion process, getting an error that says `ESXi is not in MAAS` though I have added it in the MAAS using a command mentioned in this vJailbreak's doc: https://platform9.github.io/vjailbreak/guides/cluster-conversion/maas-enablement/

Full error snippet;

```
2025-11-26T10:59:01Z    ERROR   Reconciler error        {"controller": "rollingmigrationplan", "controllerGroup": "vjailbreak.k8s.pf9.io", "controllerKind": "RollingMigrationPlan", "RollingMigrationPlan": {"name":"rolling-migration-plan-9fd930c0","namespace":"migration-system"}, "namespace": "migration-system", "name": "rolling-migration-plan-9fd930c0", "reconcileID": "7e23e0a6-11fa-46ee-929f-71402cb87ec2", "error": "failed to validate rolling migration plan: ESXi 10.X.X.X is not in MAAS", "errorVerbose": "ESXi 10.X.X.X is not in MAAS
```

Below is the image that shows machines are added to the MAAS.

Image

Machines got reflected in the MAAS after running below command which is mentioned in the doc;

```
$ maas $profile machines create deployed=true hostname=mymachine architecture=amd64 mac_addresses=<mac-address> power_type=manual
```

### What did you expect to happen?

vJailbreak should learn the systems if they are added to the MAAS.

### Environment

Version: v0.3.5

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by OmkarDeshpande7**
## What this PR does / why we need it
This PR includes
1. Changes to the cloud init to just inject necessary values, and shell scripts
2. Changes to run cloud-init script implicitly from user data
3. changes to match MAAS machines using hardwareUuid AND mac address

## Which issue(s) this PR fixes
*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #1057 
fixes #1168 

## Testing done

_please add testing details (logs, screenshots, etc.)_ 
 <div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>

<ul>

<li>This pull request introduces enhancements to the cloud-init script, allowing for better injection of necessary values and enabling implicit execution of shell scripts from user data.</li>

<li>This pull request improves the resource matching process for MAAS machines by implementing checks for both hardware UUID and MAC addresses.</li>

<li>These changes optimize the deployment process for MAAS machines, ensuring better resource management.</li>

<li>Overall, the changes touch on the cloud-init script and MAAS resource management, introducing enhancements to value injection and shell script execution.</li>

</ul>

</div>

### CODE REVIEW

File: k8s/migration/pkg/utils/bmprovisionerutils.go [hunk 1]
```diff
@@ -54,25 +54,102 @@ func ConvertESXiToPCDHost(ctx context.Context,
...
+				matchedResourceID = resources[i].Id
+				matchedResourceIdx = i
+				break
+			}
+		}
+	}
+
+	// If no UUID match found, fall back to MAC address matching
+	if matchedResourceIdx == -1 {
+		ctxlog.Info("No hardware UUID match found, trying MAC address matching")
```
Comment (sharma-tapas) [inline k8s/migration/pkg/utils/bmprovisionerutils.go]: Remove the check above for hwuuid=="" and enhance this message saying either HWUUID was nil or no match was found falling over to checking the mac addr match. And print the HWUUID value in the log.
