### PR TITLE
Detect ubuntu vm's < 17.10 and appropriately handle the networking for the interfaces 

### LINKED ISSUE #618: Unable to migrate Ubuntu 14.04 VM.
### What steps did you take and what happened?

When trying to migrate an Ubuntu 14.04 VM, the process is failing with error as below;

```
[2025-06-16T14:10:14Z] OS detected by guestfish: name="ubuntu"
version="14.04.6 lts, trusty tahr"
id=ubuntu
id_like=debian
pretty_name="ubuntu 14.04.6 lts"
version_id="14.04"
home_url="http://www.ubuntu.com/"
support_url="http://help.ubuntu.com/"
bug_report_url="http://bugs.launchpad.net/ubuntu/"
[2025-06-16T14:10:14Z] OS compatibility check passed
[2025-06-16T14:10:14Z] Setting up boot volume as: Hard disk 1
[2025-06-16T14:13:51Z] Adding wildcard netplan
[2025-06-16T14:14:12Z] failed to convert volumes: failed to add wildcard netplan: failed to run command (upload /home/fedora/99-wildcard.network /etc/systemd/network/99-wildcard.network): exit status 1. Trying to perform cleanup
[2025-06-16T14:14:20Z] Volume Hard disk 1 deleted

[2025-06-16T14:14:20Z] Failed to delete snapshot of source VM: failed to delete snapshot: no snapshots for this VM

[2025-06-16T14:14:20Z] Failed to migrate VM: failed to convert disks: Failed to delete snapshot of source VM: failed to delete snapshot: no snapshots for this VM
: failed to delete snapshot: no snapshots for this VM: failed to add wildcard netplan: failed to run command (upload /home/fedora/99-wildcard.network /etc/systemd/network/99-wildcard.network): exit status 1
VM myubun14.04 was powered on after migration failure
```

Looks like it is caused by a step in the v2v-helper attempting to configure network settings using `Netplan` or `systemd-networkd`, which are not applicable to Ubuntu 14.04 which uses the traditional `/etc/network/interfaces`.
`Netplan` in Ubuntu got introduced from version 17.10

### What did you expect to happen?

As Ubuntu 14.04 is in the list of [supported OS](https://libguestfs.org/virt-v2v-support.1.html#guests), the migration should succeed.

### Environment

Private Cloud Director - April 2025 Release.
vJailbreak - v0.1.12

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by spai-p9**
## Which issue(s) this PR fixes

*(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*

fixes #618

## Testing done: In progress.

_please add testing details (logs, screenshots, etc.)_ 
 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This PR enhances networking configurations and migration process stability by improving handling of network interfaces in CRDs and API definitions. It updates networking logic for pre-17.10 Ubuntu VMs with conditional checks for netplan support and fallback mechanisms, implementing more resilient error handling that warns rather than fails. The changes include better schema descriptions, flexible struct tags, and improved logging for diagnostics.

</div>

### CODE REVIEW

File: k8s/migration/api/v1alpha1/vmwaremachine_types.go [hunk 1]
```diff
@@ -52,6 +52,27 @@ type VMInfo struct {
...
 	RDMDisks []RDMDiskInfo `json:"rdmDisks,omitempty"`
+	// NetworkInterfaces is the list of network interfaces for the virtual machine expect the lo device
+	NetworkInterfaces []NIC `json:"networkInterfaces,omitempty"`
+	// GuestNetworks is the list of network interfaces for the virtual machine as reported by the guest
+	GuestNetworks []GuestNetwork `json:"guestNetworks,omitempty"`
+}
+
+// NIC represents a Virtual ethernet card in the virtual machine.
+type NIC struct {
+	Network string `json:"network"`
```
Comment (sharma-tapas) [inline k8s/migration/api/v1alpha1/vmwaremachine_types.go:63]: Do you need to add `omitempty` so that later on you can add nil checks?

File: v2v-helper/Dockerfile [hunk 2]
```diff
@@ -41,8 +41,7 @@ RUN curl -L -o virt-v2v-2.7.13-1.fc42.x86_64.rpm https://github.com/platform9/vj
 RUN dnf install -y \
     nbdkit \
     nbdkit-vddk-plugin \
-    libnbd \
-    virtio-win 
+    libnbd
```
Comment (sharma-tapas) [inline v2v-helper/Dockerfile:44]: why did we remove virtio-win?

File: k8s/migration/api/v1alpha1/vmwaremachine_types.go (hunk 1 above)
Comment (spai-p9) [reply k8s/migration/api/v1alpha1/vmwaremachine_types.go]: Done added omitempty.

File: v2v-helper/Dockerfile (hunk 2 above)
Comment (spai-p9) [reply v2v-helper/Dockerfile:44]: We are asking the user to download it, idk why this was there in the docker image in the first place

**Review by sarika-p9 — APPROVED** [review]

**Review by sharma-tapas — APPROVED** [review]
