### PR TITLE
fix - Vm with multiple IPs on same MAC address (Tried with 2 IPs) are not getting 2nd IP on interface post migration

### LINKED ISSUE #861: vjailbreak : For VMs with multiple Network Interfaces , ipaddress is not assigned to any of the NIC if one of NIC doesn't contain IP
### What steps did you take and what happened?

1) Tried Migrating VM with 3 Network Interfaces , one of the the nic didn't had IP address
2) VM attempted migration but got below error

Image

 

### What did you expect to happen?

Network interfaces with ip address should have been migrated , giving error for 3rd one, or user should be prompted to fix configuration in VMware

### Environment

NA

### vCenter version

NA

### Anything else you would like to add?

_No response_

### LINKED ISSUE #889: Vm with multiple IPs on same MAC address (Tried with 2 IPs) are not getting 2nd IP on interface post migration
### What steps did you take and what happened?

Vm with multiple IPs on same MAC address (Tried with 2 IPs) are not getting 2nd IP on interface post migration -

Steps -

1. Create a vcenter VM with 2 IPs on same MAC address.
2. Perform migration
3. Check below post migration -

- Both IPs should be shown configured, only one is visible 

Actual result -

PreMigration VMware side -
```
test@mnic:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:96:fe:79 brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 10.9.1.105/16 metric 100 brd 10.9.255.255 scope global dynamic ens33
       valid_lft 86361sec preferred_lft 86361sec
    inet 10.9.1.106/16 brd 10.9.255.255 scope global secondary ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe96:fe79/64 scope link 
       valid_lft forever preferred_lft forever
```

PostMigration PCD side -
```test@mnic:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:96:fe:79 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.9.2.3/16 metric 1024 brd 10.9.255.255 scope global dynamic ens3
       valid_lft 43137sec preferred_lft 43137sec
    inet6 fe80::250:56ff:fe96:fe79/64 scope link 
       valid_lft forever preferred_lft forever```

### What did you expect to happen?

Migration should be successful with same configuration (PreMigration VMware side)

### Environment

Version: v0.3.2

### vCenter version

NA

### Anything else you would like to add?

_No response_

### LINKED ISSUE #890: Vm with multiple IPs on same MAC address (Tried with 2 IPs), IP of the VM getting changed post migration
### What steps did you take and what happened?

Vm with multiple IPs on same MAC address (Tried with 2 IPs), IP of the VM getting changed post migration -

Steps -

Create a vcenter VM with 2 IPs on same MAC address.
Perform migration
Check below post migration -
IP of the VM should be same (Its different)

Actual Result -

PreMigration VMware side -

test@mnic:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:50:56:96:fe:79 brd ff:ff:ff:ff:ff:ff
    altname enp2s1
    inet 10.9.1.105/16 metric 100 brd 10.9.255.255 scope global dynamic ens33
       valid_lft 86361sec preferred_lft 86361sec
    inet 10.9.1.106/16 brd 10.9.255.255 scope global secondary ens33
       valid_lft forever preferred_lft forever
    inet6 fe80::250:56ff:fe96:fe79/64 scope link 
       valid_lft forever preferred_lft forever
PostMigration PCD side -

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:96:fe:79 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet 10.9.2.3/16 metric 1024 brd 10.9.255.255 scope global dynamic ens3
       valid_lft 43137sec preferred_lft 43137sec
    inet6 fe80::250:56ff:fe96:fe79/64 scope link 
       valid_lft forever preferred_lft forever```

### What did you expect to happen?

Migration should work with same IP get allocated to the destination VM

### Environment

Version: v0.3.2

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by meghansh-pf9**
## What this PR does / why we need it

VM with multiple IP being migrated with the same network context.
 
fixes #889 
fixes #861 
fixes #890 

## Testing done

image
image
Post Migration ip a 
image 
 <div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>

<ul>

<li>This pull request addresses a critical bug where virtual machines with multiple IPs on the same MAC address were not receiving all IPs after migration.</li>

<li>The changes enhance the netplan configuration logic to ensure correct IP assignment during the migration process.</li>

<li>A new configuration parameter, periodicSyncInterval, has been introduced to improve the migration plan.</li>

<li>Overall, this PR significantly improves the handling of network configurations for VMs during migration, touching on netplan configurations and introducing the periodicSyncInterval parameter.</li>

</ul>

</div>

### CODE REVIEW

File: k8s/migration/pkg/utils/credutils.go [hunk 1]
```diff
@@ -1710,6 +1709,8 @@ func processSingleVM(ctx context.Context, scope *scope.VMwareCredsScope, vm *obj
 	if strings.HasPrefix(vmProps.Config.Name, "vCLS-") {
 		return
 	}
+	log.Info(fmt.Sprintf("DEBUG : %v", nicList))
```
Comment (OmkarDeshpande7) [inline k8s/migration/pkg/utils/credutils.go]: remove this log

File: v2v-helper/migrate/migrate.go [hunk 2]
```diff
@@ -819,7 +819,8 @@ func (migobj *Migrate) ConvertVolumes(ctx context.Context, vminfo vm.VMInfo) err
 			if isNetplanSupported(versionID) {
 				// Add Wildcard Netplan
 				utils.PrintLog("Adding wildcard netplan")
-				err := virtv2v.AddWildcardNetplan(vminfo.VMDisks, useSingleDisk, vminfo.VMDisks[bootVolumeIndex].Path)
+				err := virtv2v.AddWildcardNetplan(vminfo.VMDisks, useSingleDisk, vminfo.VMDisks[bootVolumeIndex].Path, vminfo.GuestNetworks, vminfo.NetworkInterfaces, vminfo.GatewayIP)
+				// err := virtv2v.AddWildcardNetplan(vminfo.VMDisks, useSingleDisk, vminfo.VMDisks[bootVolumeIndex].Path)
```
Comment (OmkarDeshpande7) [inline v2v-helper/migrate/migrate.go]: leftover commented code

File: v2v-helper/migrate/migrate.go [hunk 3]
```diff
@@ -1147,11 +1148,11 @@ func (migobj *Migrate) HealthCheck(vminfo vm.VMInfo, ips []string) error {
...
-	for i := 0; i < len(vminfo.IPs); i++ {
-		if ips[i] != vminfo.IPs[i] {
-			migobj.logMessage(fmt.Sprintf("VM has been assigned a new IP: %s instead of the original IP %s. Using the new IP for tests", ips[i], vminfo.IPs[i]))
-		}
-	}
+	// for i := 0; i < len(vminfo.IPs); i++ {
+	// if ips[i] != vminfo.IPs[i] {
+	// migobj.logMessage(fmt.Sprintf("VM has been assigned a new IP: %s instead of the original IP %s. Using the new IP for tests", ips[i], vminfo.IPs[i]))
+	// }
+	// }
```
Comment (OmkarDeshpande7) [inline v2v-helper/migrate/migrate.go]: remove commented code

File: v2v-helper/virtv2v/virtv2vops.go [hunk 4]
```diff
@@ -41,6 +42,34 @@ type VirtV2VOperations interface {
...
+	} else {
+		command := "upload"
+		ans, err = RunCommandInGuestAllVolumes(disks, command, true, "/home/fedora/50-vj.yaml", "/etc/netplan/50-vj.yaml")
+	}
+	if err != nil {
+		fmt.Printf("failed to run command (%s): %v: %s\n", "upload", err, strings.TrimSpace(ans))
+		return err
+	}
+	return nil
+}
```
Comment (spai-p9) [inline v2v-helper/virtv2v/virtv2vops.go]: remove this func
