### PR TITLE
powering on of cold migration vms fix

### LINKED ISSUE #1124: Migration failure of Powered off VM Power on back the VM on vcenter
### What steps did you take and what happened?

Migration failure of Powered off VM Power on back the VM on vcenter

Tested with RDM -

RDM Migration fails, but VMs powered on back on vcenter

Steps -

1. Make sure VMs are powered off on vcenter
2. Start migration, make sure it leads to failure somewhere in VM creation steps (like no space/no host available)

Issue -
VM power on on vcenter due to migration failure.

### What did you expect to happen?

VM should keep its initial state if migration fails

### Environment

v0.3.6-rc

### vCenter version

NA

### Anything else you would like to add?

_No response_

### PR DESCRIPTION
**Pull request by meghansh-pf9**
## What this PR does / why we need it

In case of failure during cold migration, the source vm was powering on, in this PR the vm is not powered on if the migration type is cold

fixes #1124

## Testing done

**Migration Form**

image

**v2v-helper logs**
image

**State of Source VM post Failure**
image 
 <div id='description'>
<a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>

<ul>

<li>This pull request addresses a critical bug where the source VM was incorrectly powered on after a failure during cold migration, ensuring that if the migration type is cold, the VM remains powered off.</li>

<li>Improved error logging has been implemented to enhance the reliability of the migration process.</li>

<li>A new method to retrieve the VM's power state has been added, contributing to better management of VM operations.</li>

<li>Overall, this pull request addresses a critical bug in VM cold migration, enhances error logging, and adds a new method for power state retrieval.</li>

</ul>

</div>

### CODE REVIEW

**Review by sarika-pf9 — APPROVED** [review]
lgtm

File: v2v-helper/main.go [hunk 1]
```diff
@@ -146,16 +147,24 @@ func main() {
...
+		PreMigrationPowerState = types.VirtualMachinePowerStatePoweredOn
+	}
 	if err := migrationobj.MigrateVM(ctx); err != nil {
 		msg := fmt.Sprintf("Failed to migrate VM: %v", err)
 
 		// Try to power on the VM if migration failed
-		powerOnErr := vmops.VMPowerOn()
-		if powerOnErr != nil {
-			msg += fmt.Sprintf("\nAlso Failed to power on VM after migration failure: %v", powerOnErr)
+		if migrationobj.MigrationType == "cold" && PreMigrationPowerState == types.VirtualMachinePowerStatePoweredOff {
```
Comment (OmkarDeshpande7) [inline v2v-helper/main.go]:
```suggestion
		if PreMigrationPowerState == types.VirtualMachinePowerStatePoweredOff {
```
