### PR TITLE
Backend: Improve the error handling and event reporting on these failures. 

### LINKED ISSUE #392: v2v-helper pod does not exit after failure due to cleanup error and missing context cancellation
### What steps did you take and what happened?

Started a migration that failed during live disk replication.

The MigrateVM method returned an error, triggering the cleanup() method.

Inside cleanup(), snapshot deletion also failed and logged:
`Failed to delete snapshot of source VM: failed to delete snapshot: "migration-snap" resolves to 2 snapshots
`
Despite the failure, the pod (v2v-helper) remained in the Running state indefinitely.

Logs stopped progressing, indicating no further action — pod did not exit or complete.

After debugging, found that although the main function logs the failure and calls log.Fatalf, the cancel() method was not invoked before the fatal exit. This left the goroutine in UpdatePodEvents() blocking on <-ch>, keeping the pod alive.

### What did you expect to happen?

expected pod to go to completed or error state, because of this the resources are still occuppied by the pod. 

### Environment

v0.1.8

### vCenter version

NA

### Anything else you would like to add?

The fix involves:
Calling cancel() before log.Fatalf() in the main function

### PR DESCRIPTION
**Pull request by spai-p9**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #392, 
 <div id='description'>
<h3>Summary by Bito</h3>
This PR enhances error handling across multiple modules, upgrading the base image and Kubernetes libraries to version 0.33.0. It improves error recovery through case-insensitive comparison for environment variables, proper validation for volume operations, and refactors the Kubernetes migration module to better handle VM properties and disk configurations, significantly improving system stability.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 3
</div>

### CODE REVIEW

File: k8s/migration/internal/controller/migration_controller.go [hunk 1]
```diff
@@ -201,7 +206,8 @@ loop:
 			constants.StatesEnum[scope.Migration.Status.Phase] <= constants.StatesEnum[vjailbreakv1alpha1.MigrationPhaseAwaitingDataCopyStart]:
 			scope.Migration.Status.Phase = vjailbreakv1alpha1.MigrationPhaseAwaitingDataCopyStart
 			break loop
-		case strings.Contains(strings.TrimSpace(events.Items[i].Message), openstackconst.EventMessageMigrationFailed):
+		case strings.Contains(strings.TrimSpace(events.Items[i].Message), openstackconst.EventMessageMigrationFailed) ||
+			strings.Contains(strings.TrimSpace(events.Items[i].Message), openstackconst.EventMessageFailed):
```
Comment (OmkarDeshpande7) [inline k8s/migration/internal/controller/migration_controller.go:210]: Change actual event message to match `openstackconst.EventMessageMigrationFailed` instead

File: v2v-helper/main.go [hunk 2]
```diff
@@ -22,50 +22,84 @@ import (
...
+
+	// Helper function to report and handle errors
+	handleError := func(msg string) {
+		if reporter.IsRunningInPod() {
+			eventReporterChan <- msg
+			// Wait for the reporter to process the message
+			<-ackChan
+		}
+		log.Print(msg)
+		os.Exit(1)
```
Comment (OmkarDeshpande7) [inline v2v-helper/main.go:53]: do we really want to have a `os.Exit(1)` here?

File: v2v-helper/reporter/reporter.go [hunk 3]
```diff
@@ -204,6 +204,13 @@ func (r *Reporter) UpdatePodEvents(ctx context.Context, ch <-chan string) {
 						log.Println(err)
 					}
 				}
+				// Send acknowledgment that the message has been processed
+				select {
+				case ackChan <- struct{}{}:
+					// Acknowledgment sent successfully
+				default:
+					// No one expecting ack
+				}
```
Comment (OmkarDeshpande7) [inline v2v-helper/reporter/reporter.go:213]: Please add explanatory comments about why we need this?

File: k8s/migration/internal/controller/migration_controller.go (hunk 1 above)
Comment (spai-p9) [reply k8s/migration/internal/controller/migration_controller.go:210]: There are multiple failed events, would have to keep adding multiple conditions like:
`Failed to get in-cluster client:` 
`Failed to get migration parameters:`
`Failed to validate vCenter connection: `
`Failed to validate OpenStack connection: `
`Failed to get thumbprint: `
`Failed to get source VM: `
`Failed to migrate VM: `
So just added a single constant to catch these events.

File: v2v-helper/reporter/reporter.go (hunk 3 above)
Comment (spai-p9) [reply v2v-helper/reporter/reporter.go]: Added the comment.

File: v2v-helper/main.go (hunk 2 above)
Comment (spai-p9) [reply v2v-helper/main.go]: Yeah it is not needed, changed it to return.

File: v2v-helper/main.go [hunk 4]
```diff
@@ -22,50 +22,84 @@ import (
...
-	var vCenterPassword = strings.TrimSpace(os.Getenv("VCENTER_PASSWORD"))
-	var vCenterInsecure = strings.TrimSpace(os.Getenv("VCENTER_INSECURE")) == constants.TrueString
-	var openstackInsecure = strings.EqualFold(strings.TrimSpace(os.Getenv("OS_INSECURE")), constants.TrueString)
+
+	var (
+		vCenterURL        = strings.TrimSpace(os.Getenv("VCENTER_HOST"))
+		vCenterUserName   = strings.TrimSpace(os.Getenv("VCENTER_USERNAME"))
+		vCenterPassword   = strings.TrimSpace(os.Getenv("VCENTER_PASSWORD"))
+		vCenterInsecure   = strings.TrimSpace(os.Getenv("VCENTER_INSECURE")) == constants.TrueString
+		openstackInsecure = strings.TrimSpace(os.Getenv("OS_INSECURE")) == constants.TrueString
```
Comment (sharma-tapas) [inline v2v-helper/main.go:71]: Use strings.Equalfold for case insensitive comparison. Pass it the trim spaces output

Comment (spai-p9) [reply v2v-helper/main.go]: Done.

File: v2v-helper/migrate/migrate.go [hunk 5]
```diff
@@ -819,36 +819,49 @@ func (migobj *Migrate) MigrateVM(ctx context.Context) error {
...
 		log.Printf("Failed to detach all volumes from VM: %s\n", err)
+		return errors.Wrap(err, "failed to detach volumes")
 	} else if err = migobj.DeleteAllVolumes(vminfo); err != nil {
 		log.Printf("Failed to delete all volumes from host: %s\n", err)
+		return errors.Wrap(err, "failed to delete volumes")
 	}
 	err = migobj.VMops.DeleteSnapshot(constants.MigrationSnapshotName)
 	if err != nil {
 		log.Printf("Failed to delete snapshot of source VM: %s\n", err)
+		return errors.Wrap(err, "failed to delete snapshot")
```
Comment (OmkarDeshpande7) [inline v2v-helper/migrate/migrate.go:864]:
```suggestion
		log.Printf("Failed to delete snapshot of source VM: %s\n", err)
		return errors.Wrap(err, fmt.Sprintf("Failed to delete snapshot of source VM: %s\n", err))
```

**Review by OmkarDeshpande7 — APPROVED** [review]
